name: app_blog
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  asyncstate: ^2.0.2
  loading_animation_widget: ^1.2.0+4
  super_editor: ^0.2.6
  cupertino_icons: ^1.0.2
  modal_bottom_sheet: ^2.1.2
  google_fonts:
  flutter_snake_navigationbar: ^0.6.1
  advanced_icon: ^0.1.2
  line_icons: ^2.0.3
  get: ^4.2.0
  firebase_auth: ^4.7.2
  firebase_core:
  firebase_storage:
  cloud_firestore: ^4.8.4
  google_sign_in:
  provider:
  mobx:
  flutter_mobx:
  image_picker: ^1.0.2
  path_provider: ^2.0.15
  lottie:
  connectivity_plus: ^4.0.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  exists_in: ^0.0.1
  flutter_slidable: ^3.0.0
  firebase_messaging:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen:
  build_runner:

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/json/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
